#!/usr/bin/env python3
"""Erzeugt die mitgelieferte Startdatenbank ``data/seed/ingredients.json``.

Diese Datei ist die *Quelle der Wahrheit* für die ausgelieferten Zutatenwerte.
Sie ist bewusst ein Generator und keine handgepflegte JSON-Datei, weil damit

* jeder Wert eine nachvollziehbare Quelle bekommt,
* der Brennwert nicht abgetippt, sondern nach Anhang XIV der VO (EU)
  Nr. 1169/2011 aus den Nährstoffen **berechnet** wird, und
* die Datenbank jederzeit reproduzierbar neu erzeugt werden kann.

Aufruf::

    python tools/build_seed_database.py

Konventionen der Tabelle unten
------------------------------
``carbs``
    Kohlenhydrate nach EU-Konvention, also **ohne** Ballaststoffe. Bei Werten
    aus der USDA-Datenbank wurden die Ballaststoffe vorher abgezogen; genau
    dieses Detail war die Ursache mehrerer Fehler in der Altdatenbank.
``energy``
    Nur setzen, wenn ein Etikettwert bewusst dem berechneten vorgezogen wird.
    Sonst wird gerechnet.
``water``
    Durchweg fachlich abgeleitet (Handelsüblichkeit, Massenbilanz), weil dieser
    Wert auf keinem Etikett steht.
"""

from __future__ import annotations

import json
import sys
from datetime import date
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from brotrechner import __version__
from brotrechner.core.models import Category, Ingredient, Source
from brotrechner.core.nutrients import Nutrients, energy_from_macros
from brotrechner.core.validation import Severity, validate_database
from brotrechner.data.repository import SCHEMA_VERSION

OUTPUT = Path(__file__).resolve().parents[1] / "src/brotrechner/data/seed/ingredients.json"

#: Preisstand aller recherchierten und geschätzten Preise.
PRICE_DATE = "2026-08-16"

# Quellenkürzel für price_source
RESEARCHED = "recherchiert"
ESTIMATE = "Schätzung Discounter-Niveau"
DERIVED = "aus Zutatenkosten berechnet"

# Referenzquellen für nutrition_source-Kommentare
USDA = "USDA FoodData Central, auf EU-Konvention umgerechnet"
LABEL_DE = "Handelsübliche deutsche Etikettwerte"
CALC = "berechnet aus der Rezeptur"

F = Category.FLOUR
G = Category.GRAINS
S = Category.SEEDS_NUTS
L = Category.LEAVENING
B = Category.BASICS
O = Category.FATS_OILS  # noqa: E741 - "oil"
D = Category.DAIRY
W = Category.SPICES
X = Category.OTHER


def n(
    fat: float,
    sat: float,
    carbs: float,
    sugar: float,
    protein: float,
    fiber: float,
    salt: float,
    water: float,
    *,
    energy: float | None = None,
) -> Nutrients:
    """Baut einen Nährwertvektor; der Brennwert wird berechnet, wenn nicht gesetzt."""
    base = Nutrients(
        fat=fat,
        saturated_fat=sat,
        carbs=carbs,
        sugar=sugar,
        protein=protein,
        fiber=fiber,
        salt=salt,
        water=water,
    )
    kcal = energy if energy is not None else round(energy_from_macros(base))
    return base.with_values(energy_kcal=kcal)


# ═══════════════════════════════════════════════════════════════════════════
#  Zutatentabelle
#
#  Spalten: (name, hersteller, kategorie, ist_mehl, nährwerte, preis, größe_g,
#            preisquelle, nährwertquelle, notiz)
# ═══════════════════════════════════════════════════════════════════════════

# fmt: off - die kompakte Tabellenform ist hier absichtlich; automatisches
# Umformatieren würde jede Zeile auf zehn aufblähen und die Lesbarkeit zerstören.
TABLE: list[tuple[str, str, Category, bool, Nutrients, float, float, str, str, str]] = [
    # ── Mehle ──────────────────────────────────────────────────────────────
    (
        "Weizenmehl Type 405",
        "",
        F,
        True,
        n(1.0, 0.2, 72.0, 0.7, 10.0, 3.5, 0.01, 13.0),
        0.45,
        1000,
        f"{RESEARCHED}: Lidl Eigenmarke 1 kg",
        LABEL_DE,
        "",
    ),
    (
        "Weizenmehl Type 550",
        "",
        F,
        True,
        n(1.0, 0.2, 70.0, 0.7, 11.0, 4.0, 0.01, 13.5),
        0.55,
        1000,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Weizenmehl Type 1050",
        "",
        F,
        True,
        n(1.4, 0.3, 66.0, 0.9, 11.5, 5.5, 0.01, 13.5),
        0.85,
        1000,
        f"{RESEARCHED}: Aldi Süd Gut Bio 1 kg",
        LABEL_DE,
        "",
    ),
    (
        "Weizenvollkornmehl",
        "",
        F,
        True,
        n(2.0, 0.4, 58.0, 1.2, 12.0, 11.0, 0.01, 13.0),
        0.85,
        1000,
        f"{RESEARCHED}: Aldi Süd Gut Bio 1 kg",
        LABEL_DE,
        "",
    ),
    (
        "Roggenmehl Type 997",
        "",
        F,
        True,
        n(1.0, 0.2, 68.0, 1.2, 7.0, 7.5, 0.01, 13.5),
        1.49,
        1000,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Roggenmehl Type 1150",
        "",
        F,
        True,
        n(1.2, 0.2, 65.0, 1.3, 8.0, 9.0, 0.01, 13.5),
        1.49,
        1000,
        f"{RESEARCHED}: Rewe Diamant 1 kg",
        LABEL_DE,
        "",
    ),
    (
        "Roggenmehl Type 1370",
        "",
        F,
        True,
        n(1.4, 0.2, 62.0, 1.4, 8.5, 11.0, 0.01, 13.5),
        1.79,
        1000,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Roggenvollkornmehl",
        "",
        F,
        True,
        n(1.7, 0.3, 60.0, 1.0, 8.5, 14.0, 0.01, 13.0),
        1.78,
        1000,
        f"{RESEARCHED}: Rewe Bio 500 g für 0,89 €",
        LABEL_DE,
        "Eiweiß korrigiert: 13 g war ein Wert für Weizen; Roggenvollkorn liegt bei 8-9 g.",
    ),
    (
        "Dinkelmehl Type 630",
        "",
        F,
        True,
        n(1.4, 0.3, 69.0, 1.0, 11.0, 4.0, 0.01, 13.0),
        1.29,
        1000,
        f"{RESEARCHED}: Lidl Belbake 1 kg",
        LABEL_DE,
        "",
    ),
    (
        "Dinkelmehl Type 1050",
        "",
        F,
        True,
        n(1.8, 0.3, 65.0, 1.0, 12.0, 6.0, 0.01, 13.0),
        1.29,
        1000,
        f"{RESEARCHED}: Lidl Belbake 1 kg",
        LABEL_DE,
        "",
    ),
    (
        "Dinkelvollkornmehl",
        "",
        F,
        True,
        n(2.4, 0.4, 59.0, 1.2, 13.0, 9.5, 0.01, 12.5),
        0.99,
        1000,
        f"{RESEARCHED}: Aldi Süd Mühlengold 1 kg",
        LABEL_DE,
        "",
    ),
    (
        "Emmermehl Vollkorn",
        "",
        F,
        True,
        n(2.4, 0.4, 58.0, 1.0, 14.0, 9.0, 0.01, 12.5),
        4.50,
        1000,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Einkornmehl Vollkorn",
        "",
        F,
        True,
        n(2.8, 0.5, 58.0, 1.2, 14.5, 8.0, 0.01, 12.5),
        5.50,
        1000,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Buchweizenmehl",
        "",
        F,
        True,
        n(1.7, 0.4, 68.0, 1.0, 9.0, 4.5, 0.01, 12.5),
        3.50,
        1000,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Maismehl",
        "",
        F,
        True,
        n(1.2, 0.2, 74.0, 0.6, 7.0, 4.0, 0.01, 12.0),
        2.20,
        1000,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Reismehl",
        "",
        F,
        True,
        n(0.6, 0.2, 78.5, 0.1, 6.0, 2.0, 0.01, 12.0),
        2.80,
        1000,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Kartoffelstärke",
        "",
        F,
        True,
        n(0.1, 0.0, 81.0, 0.0, 0.1, 0.0, 0.01, 18.0),
        0.79,
        400,
        ESTIMATE,
        LABEL_DE,
        "Kartoffelstärke ist stark hygroskopisch und hält handelsüblich 18-20 % Wasser.",
    ),
    # ── Mehle mit Hersteller ───────────────────────────────────────────────
    (
        "Roggenvollkornmehl",
        "Bauck",
        F,
        True,
        n(1.7, 0.3, 60.0, 1.0, 8.5, 14.0, 0.01, 13.0),
        1.98,
        1000,
        f"{RESEARCHED}: memo.de, Bauckhof demeter 1 kg",
        LABEL_DE,
        "",
    ),
    (
        "Roggenvollkornmehl",
        "Spielberger",
        F,
        True,
        n(1.7, 0.3, 60.0, 1.0, 8.5, 14.0, 0.01, 13.0),
        2.79,
        1000,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Roggenvollkornmehl",
        "Alnatura",
        F,
        True,
        n(1.7, 0.3, 60.0, 1.0, 8.5, 14.0, 0.01, 13.0),
        1.99,
        1000,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Dinkelvollkornmehl",
        "dm Bio",
        F,
        True,
        n(2.4, 0.4, 59.0, 1.2, 13.0, 9.5, 0.01, 12.5),
        1.95,
        1000,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Dinkelvollkornmehl",
        "Alnatura",
        F,
        True,
        n(2.4, 0.4, 59.0, 1.2, 13.0, 9.5, 0.01, 12.5),
        2.29,
        1000,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Dinkelmehl Type 630",
        "Aldi",
        F,
        True,
        n(1.4, 0.3, 69.0, 1.0, 11.0, 4.0, 0.01, 13.0),
        1.49,
        1000,
        f"{RESEARCHED}: Aldi Süd Goldähren 1 kg",
        LABEL_DE,
        "",
    ),
    (
        "Dinkelmehl Type 630",
        "Rewe",
        F,
        True,
        n(1.4, 0.3, 69.0, 1.0, 11.0, 4.0, 0.01, 13.0),
        1.79,
        1000,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Weizenmehl Type 550",
        "Aldi",
        F,
        True,
        n(1.0, 0.2, 70.0, 0.7, 11.0, 4.0, 0.01, 13.5),
        0.55,
        1000,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Weizenvollkornmehl",
        "Alnatura",
        F,
        True,
        n(2.0, 0.4, 58.0, 1.2, 12.0, 11.0, 0.01, 13.0),
        1.99,
        1000,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    # ── Saaten & Kerne ─────────────────────────────────────────────────────
    (
        "Sonnenblumenkerne",
        "",
        S,
        False,
        n(49.0, 5.2, 12.0, 2.6, 21.0, 8.0, 0.03, 5.0),
        1.79,
        400,
        f"{RESEARCHED}: Lidl Alesto 400 g",
        USDA,
        "",
    ),
    (
        "Leinsamen",
        "",
        S,
        False,
        n(42.2, 3.7, 1.6, 1.6, 18.3, 27.3, 0.08, 7.0),
        1.49,
        500,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Kürbiskerne",
        "",
        S,
        False,
        n(49.0, 8.7, 4.7, 1.4, 30.2, 6.0, 0.02, 5.5),
        1.93,
        200,
        f"{RESEARCHED}: Lidl Alesto naturbelassen 200 g",
        USDA,
        "Kohlenhydrate von 10,7 auf 4,7 g korrigiert: der alte Wert enthielt die "
        "Ballaststoffe noch (US-Konvention).",
    ),
    (
        "Sesam",
        "",
        S,
        False,
        n(49.7, 7.0, 11.7, 0.3, 17.7, 11.8, 0.02, 5.0),
        1.29,
        250,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Mohn (blau)",
        "",
        S,
        False,
        n(41.6, 4.5, 8.6, 3.0, 18.0, 19.5, 0.02, 6.0),
        1.49,
        250,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Chiasamen",
        "",
        S,
        False,
        n(30.7, 3.3, 7.7, 0.0, 16.5, 34.4, 0.03, 6.0),
        2.99,
        400,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Flohsamenschalen",
        "",
        S,
        False,
        n(0.5, 0.1, 1.7, 0.0, 2.4, 83.7, 0.03, 8.0),
        4.95,
        500,
        ESTIMATE,
        CALC,
        "Brennwert von 21 auf 188 kcal korrigiert. Anhang XIV der VO (EU) 1169/2011 "
        "schreibt für Ballaststoffe 2 kcal/g vor; viele Etiketten lassen diesen "
        "Anteil weg.",
    ),
    (
        "Walnüsse",
        "",
        S,
        False,
        n(65.2, 6.1, 7.0, 2.6, 15.2, 6.7, 0.01, 4.0),
        4.99,
        500,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Haselnüsse",
        "",
        S,
        False,
        n(60.8, 4.5, 7.0, 4.3, 15.0, 9.7, 0.01, 5.3),
        3.49,
        200,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Mandeln",
        "",
        S,
        False,
        n(49.9, 3.8, 9.1, 4.4, 21.2, 12.5, 0.01, 4.4),
        2.99,
        200,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Hanfsamen (geschält)",
        "",
        S,
        False,
        n(48.8, 4.6, 4.7, 1.5, 31.6, 4.0, 0.01, 5.0),
        4.99,
        500,
        ESTIMATE,
        USDA,
        "",
    ),
    # ── Getreide & Flocken ─────────────────────────────────────────────────
    (
        "Haferflocken",
        "",
        G,
        False,
        n(7.0, 1.3, 58.7, 1.0, 13.5, 10.0, 0.02, 10.0),
        0.75,
        500,
        ESTIMATE,
        LABEL_DE,
        "Kohlenhydrate von 63,3 auf 58,7 g und Wasser von 12 auf 10 % korrigiert; "
        "die Massenbilanz lag vorher bei 105,8 g je 100 g.",
    ),
    (
        "Haferkleie",
        "",
        G,
        False,
        n(7.0, 1.3, 50.8, 1.5, 17.3, 15.4, 0.02, 6.6),
        1.85,
        500,
        f"{RESEARCHED}: dm Bio 500 g",
        USDA,
        "Brennwert von 246 auf 367 kcal und Kohlenhydrate von 30 auf 50,8 g korrigiert.",
    ),
    (
        "Hafer (ganz)",
        "",
        G,
        False,
        n(7.0, 1.3, 58.0, 1.0, 13.5, 10.0, 0.01, 11.0),
        2.45,
        1000,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Weizenkleie",
        "",
        G,
        False,
        n(4.3, 0.6, 21.7, 0.4, 15.6, 42.8, 0.01, 9.9),
        1.49,
        500,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Weizenkeime",
        "",
        G,
        False,
        n(9.7, 1.7, 38.6, 8.0, 23.2, 13.2, 0.01, 11.1),
        2.49,
        250,
        ESTIMATE,
        USDA,
        "Eiweiß von 32 auf 23,2 g korrigiert; die Massenbilanz lag vorher bei 107,9 g je 100 g.",
    ),
    (
        "Backmalz (inaktiv)",
        "",
        G,
        False,
        n(1.5, 0.3, 71.0, 20.0, 10.0, 4.0, 0.02, 8.0),
        3.49,
        500,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Grünkern",
        "",
        G,
        False,
        n(2.7, 0.5, 60.0, 1.0, 11.6, 8.8, 0.01, 12.0),
        2.95,
        500,
        f"{RESEARCHED}: dm Bio fränkischer Grünkern 500 g",
        LABEL_DE,
        "",
    ),
    (
        "Dinkel (ganz)",
        "",
        G,
        False,
        n(2.4, 0.4, 58.5, 2.6, 14.6, 10.7, 0.01, 11.0),
        2.29,
        1000,
        ESTIMATE,
        USDA,
        "Massenbilanz lag vorher bei 103,2 g je 100 g.",
    ),
    (
        "Amaranth",
        "",
        G,
        False,
        n(7.0, 1.5, 58.6, 1.7, 13.6, 6.7, 0.01, 11.3),
        3.49,
        500,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Hirse",
        "",
        G,
        False,
        n(4.2, 0.7, 64.4, 0.0, 11.0, 8.5, 0.01, 8.7),
        2.29,
        500,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Quinoa",
        "",
        G,
        False,
        n(6.1, 0.7, 57.2, 2.0, 14.1, 7.0, 0.01, 13.3),
        3.29,
        500,
        ESTIMATE,
        USDA,
        "",
    ),
    # ── Getreide mit Hersteller ────────────────────────────────────────────
    (
        "Haferkleie",
        "dm Bio",
        G,
        False,
        n(7.0, 1.3, 50.8, 1.5, 17.3, 15.4, 0.02, 6.6),
        1.85,
        500,
        f"{RESEARCHED}: dm.de, dmBio Haferkleie mit Keim 500 g",
        USDA,
        "",
    ),
    (
        "Haferflocken Großblatt",
        "Bauck",
        G,
        False,
        n(7.0, 1.3, 58.7, 1.0, 13.5, 10.0, 0.02, 10.0),
        2.29,
        500,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Hafer (ganz)",
        "dm",
        G,
        False,
        n(7.0, 1.3, 58.0, 1.0, 13.5, 10.0, 0.01, 11.0),
        2.45,
        1000,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Dinkel (ganz)",
        "Alnatura",
        G,
        False,
        n(2.4, 0.4, 58.5, 2.6, 14.6, 10.7, 0.01, 11.0),
        2.79,
        1000,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Grünkern fränkisch",
        "dm",
        G,
        False,
        n(2.7, 0.5, 60.0, 1.0, 11.6, 8.8, 0.01, 12.0),
        2.95,
        500,
        f"{RESEARCHED}: dm.de, dmBio fränkischer Grünkern 500 g",
        LABEL_DE,
        "",
    ),
    # ── Triebmittel ────────────────────────────────────────────────────────
    (
        "Hefe (frisch)",
        "",
        L,
        False,
        n(1.9, 0.4, 5.0, 1.0, 14.0, 6.0, 0.10, 70.0),
        0.13,
        42,
        ESTIMATE,
        LABEL_DE,
        "Brennwert von 94 auf 105 kcal korrigiert; die alten Kohlenhydrate (2 g) "
        "passten nicht zum angegebenen Brennwert.",
    ),
    (
        "Trockenhefe",
        "",
        L,
        False,
        n(4.6, 0.6, 18.0, 5.0, 45.0, 20.0, 0.10, 5.0),
        0.79,
        28,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Sauerteig Anstellgut (Roggen)",
        "",
        L,
        False,
        n(0.9, 0.1, 27.5, 0.5, 4.3, 7.0, 0.01, 56.5),
        0.89,
        1000,
        DERIVED,
        CALC,
        "Neu berechnet für Anstellgut mit Teigausbeute 200 (Mehl : Wasser = 1 : 1) "
        "abzüglich rund 8 % Gärverlust. Die alten Werte (63 kcal, 12 g KH) "
        "entsprachen keiner nachvollziehbaren Führung.",
    ),
    (
        "Lievito Madre (Weizensauer)",
        "",
        L,
        False,
        n(0.7, 0.1, 43.0, 0.5, 7.3, 2.7, 0.01, 42.3),
        0.37,
        1000,
        DERIVED,
        CALC,
        "Neu berechnet für einen festen Weizensauer mit Teigausbeute 150 "
        "abzüglich rund 8 % Gärverlust.",
    ),
    (
        "Backpulver",
        "",
        L,
        False,
        n(0.1, 0.1, 22.0, 0.0, 0.1, 0.0, 44.0, 0.0, energy=91),
        0.55,
        80,
        ESTIMATE,
        LABEL_DE,
        "Werte nach Dr. Oetker Backin als Marktstandard. Formulierungen anderer "
        "Hersteller weichen im Salzgehalt deutlich ab.",
    ),
    (
        "Sauerteigpulver",
        "",
        L,
        False,
        n(1.5, 0.3, 60.0, 2.0, 9.0, 8.0, 0.10, 8.0),
        1.49,
        150,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    # ── Grundzutaten ───────────────────────────────────────────────────────
    (
        "Wasser",
        "",
        B,
        False,
        n(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 100.0),
        0.0045,
        1000,
        "Trink- und Abwasser, Mittelwert Deutschland",
        CALC,
        "Kosten je Liter inklusive Abwassergebühr.",
    ),
    (
        "Salz",
        "",
        B,
        False,
        n(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 100.0, 0.0),
        0.19,
        500,
        ESTIMATE,
        LABEL_DE,
        "Günstigstes Speisesalz (jodiert), Discounter.",
    ),
    (
        "Zucker",
        "",
        B,
        False,
        n(0.0, 0.0, 100.0, 100.0, 0.0, 0.0, 0.0, 0.0),
        0.89,
        1000,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Honig",
        "",
        B,
        False,
        n(0.0, 0.0, 80.0, 80.0, 0.3, 0.0, 0.01, 17.0),
        2.99,
        500,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Rübenkraut",
        "",
        B,
        False,
        n(0.0, 0.0, 74.0, 66.0, 1.5, 0.0, 0.10, 22.0),
        2.19,
        450,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Malzextrakt",
        "",
        B,
        False,
        n(0.0, 0.0, 78.0, 50.0, 1.5, 0.0, 0.05, 20.0),
        3.99,
        450,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    # ── Fette & Öle ────────────────────────────────────────────────────────
    (
        "Olivenöl",
        "",
        O,
        False,
        n(100.0, 14.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, energy=884),
        5.99,
        687,
        ESTIMATE,
        LABEL_DE,
        "750 ml entsprechen rund 687 g (Dichte 0,916 g/ml).",
    ),
    (
        "Sonnenblumenöl",
        "",
        O,
        False,
        n(100.0, 10.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, energy=884),
        1.99,
        920,
        ESTIMATE,
        LABEL_DE,
        "1 l entspricht rund 920 g (Dichte 0,92 g/ml).",
    ),
    (
        "Rapsöl",
        "",
        O,
        False,
        n(100.0, 7.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, energy=884),
        1.99,
        920,
        ESTIMATE,
        LABEL_DE,
        "1 l entspricht rund 920 g (Dichte 0,92 g/ml).",
    ),
    (
        "Butter",
        "",
        O,
        False,
        n(82.0, 52.0, 0.6, 0.6, 0.7, 0.0, 0.04, 16.0, energy=741),
        2.19,
        250,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Kürbiskernöl",
        "",
        O,
        False,
        n(100.0, 19.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, energy=884),
        6.95,
        231,
        ESTIMATE,
        LABEL_DE,
        "250 ml entsprechen rund 231 g (Dichte 0,925 g/ml).",
    ),
    (
        "Kokosöl",
        "",
        O,
        False,
        n(100.0, 82.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, energy=884),
        3.99,
        450,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Margarine",
        "",
        O,
        False,
        n(80.0, 20.0, 0.4, 0.4, 0.2, 0.0, 0.60, 18.0, energy=722),
        1.19,
        500,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Butterschmalz",
        "",
        O,
        False,
        n(99.5, 62.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, energy=897),
        3.49,
        500,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Kürbiskernöl",
        "dm Bio",
        O,
        False,
        n(100.0, 19.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, energy=884),
        6.95,
        231,
        ESTIMATE,
        LABEL_DE,
        "250 ml entsprechen rund 231 g (Dichte 0,925 g/ml).",
    ),
    # ── Milchprodukte ──────────────────────────────────────────────────────
    (
        "Milch (3,5%)",
        "",
        D,
        False,
        n(3.5, 2.3, 4.8, 4.8, 3.3, 0.0, 0.10, 87.5),
        1.15,
        1030,
        ESTIMATE,
        LABEL_DE,
        "1 l entspricht rund 1030 g.",
    ),
    (
        "Buttermilch",
        "",
        D,
        False,
        n(0.5, 0.3, 4.0, 4.0, 3.5, 0.0, 0.10, 91.0),
        0.99,
        500,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Joghurt (natur, 3,5%)",
        "",
        D,
        False,
        n(3.5, 2.3, 4.8, 4.8, 3.6, 0.0, 0.10, 86.0),
        0.89,
        500,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Joghurt (1,5% Fett)",
        "",
        D,
        False,
        n(1.5, 1.0, 4.8, 4.8, 4.3, 0.0, 0.10, 88.0),
        0.65,
        500,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Joghurt (griechisch, 10%)",
        "",
        D,
        False,
        n(10.0, 6.5, 4.0, 4.0, 6.5, 0.0, 0.10, 76.0),
        1.49,
        500,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Quark (Magerquark)",
        "",
        D,
        False,
        n(0.3, 0.2, 4.0, 4.0, 13.0, 0.0, 0.10, 80.0),
        0.99,
        500,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Schmand",
        "",
        D,
        False,
        n(24.0, 15.0, 3.0, 3.0, 3.0, 0.0, 0.10, 68.0),
        0.79,
        200,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Sahne",
        "",
        D,
        False,
        n(31.7, 20.0, 3.4, 3.4, 2.4, 0.0, 0.07, 62.0),
        1.09,
        200,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Skyr",
        "",
        D,
        False,
        n(0.2, 0.1, 4.0, 4.0, 11.0, 0.0, 0.10, 82.0),
        1.19,
        450,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Milchpulver (Vollmilch)",
        "",
        D,
        False,
        n(27.0, 17.0, 38.0, 38.0, 26.0, 0.0, 0.90, 3.0),
        4.99,
        400,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Frischkäse (Doppelrahm)",
        "",
        D,
        False,
        n(24.5, 16.0, 3.0, 3.0, 6.0, 0.0, 0.60, 61.0),
        1.19,
        200,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Crème fraîche",
        "",
        D,
        False,
        n(30.0, 20.0, 2.5, 2.5, 2.8, 0.0, 0.08, 63.0),
        0.99,
        200,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    # ── Gewürze ────────────────────────────────────────────────────────────
    (
        "Brotgewürz (Mischung)",
        "",
        W,
        False,
        n(17.0, 1.0, 20.0, 1.5, 16.0, 35.0, 0.10, 9.0),
        1.99,
        50,
        ESTIMATE,
        CALC,
        "Aus den Einzelgewürzen Koriander, Fenchel, Kümmel und Anis gemittelt; "
        "die alte Massenbilanz war nicht schlüssig.",
    ),
    (
        "Kümmel",
        "",
        W,
        False,
        n(14.6, 0.6, 11.9, 0.6, 19.8, 38.0, 0.17, 9.9),
        1.29,
        50,
        ESTIMATE,
        USDA,
        "Kohlenhydrate von 33,7 auf 11,9 g korrigiert; die Massenbilanz lag vorher "
        "bei 124 g je 100 g.",
    ),
    (
        "Koriandersamen",
        "",
        W,
        False,
        n(17.8, 1.0, 13.1, 0.5, 12.4, 41.9, 0.04, 8.9),
        1.29,
        40,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Fenchelsamen",
        "",
        W,
        False,
        n(14.9, 0.5, 12.5, 0.0, 15.8, 39.8, 0.09, 8.8),
        1.29,
        40,
        ESTIMATE,
        USDA,
        "Kohlenhydrate von 36,6 auf 12,5 g korrigiert; die Massenbilanz lag vorher "
        "bei 116,2 g je 100 g.",
    ),
    (
        "Anissamen",
        "",
        W,
        False,
        n(15.9, 0.6, 35.4, 0.0, 17.6, 14.6, 0.02, 9.5),
        1.49,
        40,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Schwarzkümmel (Nigella)",
        "",
        W,
        False,
        n(35.0, 3.0, 12.0, 2.0, 20.0, 22.0, 0.04, 6.0),
        2.49,
        100,
        ESTIMATE,
        USDA,
        "",
    ),
    # ── Sonstiges ──────────────────────────────────────────────────────────
    (
        "Ei",
        "",
        X,
        False,
        n(10.6, 3.2, 1.1, 1.1, 12.6, 0.0, 0.35, 75.0),
        2.99,
        500,
        ESTIMATE,
        USDA,
        "Packungsgröße = 10 Eier Größe M ohne Schale (je rund 50 g).",
    ),
    (
        "Apfel (frisch)",
        "",
        X,
        False,
        n(0.4, 0.1, 11.4, 10.3, 0.3, 2.0, 0.01, 85.0),
        2.49,
        1000,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Kartoffel (gekocht)",
        "",
        X,
        False,
        n(0.1, 0.0, 14.6, 0.8, 1.9, 1.8, 0.01, 80.0),
        1.29,
        1000,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Gluten (Weizenkleber)",
        "",
        X,
        False,
        n(1.8, 0.3, 14.0, 0.5, 75.0, 0.5, 0.04, 8.0),
        6.99,
        1000,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Gluten rein",
        "Grünland",
        X,
        False,
        n(1.8, 0.3, 14.0, 0.5, 75.0, 0.5, 0.04, 8.0),
        7.99,
        1000,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Leinmehl (teilentölt)",
        "",
        X,
        True,
        n(12.0, 1.1, 1.0, 1.0, 39.0, 34.0, 0.08, 8.0),
        3.49,
        500,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Leinmehl (teilentölt)",
        "Rapunzel",
        X,
        True,
        n(12.0, 1.1, 1.0, 1.0, 39.0, 34.0, 0.08, 8.0),
        4.29,
        500,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Sojamehl",
        "",
        X,
        True,
        n(20.7, 3.0, 24.3, 7.5, 34.5, 9.6, 0.01, 5.2),
        3.49,
        500,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Essig",
        "",
        X,
        False,
        n(0.0, 0.0, 0.3, 0.0, 0.0, 0.0, 0.0, 94.0, energy=5),
        0.69,
        1005,
        ESTIMATE,
        LABEL_DE,
        "",
    ),
    (
        "Rosinen",
        "",
        X,
        False,
        n(0.5, 0.1, 68.0, 59.0, 3.1, 3.7, 0.05, 15.0),
        1.49,
        500,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Cranberries (getrocknet)",
        "",
        X,
        False,
        n(1.4, 0.1, 72.0, 65.0, 0.2, 5.7, 0.01, 15.0),
        2.49,
        200,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Feigen (getrocknet)",
        "",
        X,
        False,
        n(0.9, 0.2, 53.0, 48.0, 3.3, 9.8, 0.01, 24.0),
        2.99,
        400,
        ESTIMATE,
        USDA,
        "",
    ),
    (
        "Altbrot (Paniermehl)",
        "",
        X,
        False,
        n(5.3, 1.2, 64.0, 3.0, 13.4, 4.5, 1.20, 6.5),
        0.85,
        1000,
        f"{RESEARCHED}: Lidl Gut Frielingshof 1 kg",
        LABEL_DE,
        "Zählt nicht mehr als Mehl: Paniermehl ist bereits gebackenes Brot und "
        "gehört im Bäckerprozent nicht zur Mehlmenge. Die alte Namens-Heuristik "
        "hatte es wegen der Silbe 'mehl' als Mehl gewertet.",
    ),
    (
        "Oliven (schwarz)",
        "",
        X,
        False,
        n(11.0, 1.5, 3.0, 0.0, 0.8, 2.5, 3.50, 75.0),
        1.29,
        200,
        ESTIMATE,
        USDA,
        "Packungsgröße = Abtropfgewicht.",
    ),
    (
        "Tomatenmark",
        "",
        X,
        False,
        n(0.5, 0.1, 12.0, 12.0, 4.5, 4.0, 1.00, 74.0),
        0.59,
        200,
        ESTIMATE,
        USDA,
        "",
    ),
]
# fmt: on


def build() -> list[Ingredient]:
    """Baut die Zutatenliste aus der Tabelle."""
    stand = date.fromisoformat(PRICE_DATE)
    ingredients: list[Ingredient] = []
    for name, manufacturer, category, is_flour, nutrients, price, size, psrc, nsrc, note in TABLE:
        ingredients.append(
            Ingredient(
                name=name,
                manufacturer=manufacturer,
                category=category,
                nutrients=nutrients,
                is_flour=is_flour,
                package_price=price,
                package_size_g=size,
                price_source=psrc,
                price_updated=stand,
                nutrition_source=Source.REFERENCE,
                water_source=Source.ESTIMATED,
                notes=" ".join(filter(None, [note, f"Nährwertquelle: {nsrc}."])),
            )
        )
    return ingredients


def main() -> int:
    """Erzeugt die Datei und prüft sie sofort; Fehler brechen ab."""
    ingredients = build()

    keys = [i.key for i in ingredients]
    duplicates = {k for k in keys if keys.count(k) > 1}
    if duplicates:
        print(f"FEHLER: doppelte Schlüssel: {sorted(duplicates)}", file=sys.stderr)
        return 1

    findings = validate_database(ingredients)
    errors = [f for f in findings if f.severity is Severity.ERROR]
    warnings = [f for f in findings if f.severity is Severity.WARNING]

    for finding in errors + warnings:
        print(f"  {finding}", file=sys.stderr)

    if errors:
        print(f"FEHLER: {len(errors)} Bilanzfehler in der Startdatenbank", file=sys.stderr)
        return 1

    payload: dict[str, Any] = {
        "schema_version": SCHEMA_VERSION,
        "generator": f"tools/build_seed_database.py (brotrechner {__version__})",
        "price_date": PRICE_DATE,
        "ingredients": [
            i.to_dict() for i in sorted(ingredients, key=lambda x: x.display_name.casefold())
        ],
    }
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(f"{len(ingredients)} Zutaten geschrieben nach {OUTPUT}")
    print(f"  {len(warnings)} Warnungen, 0 Fehler")
    priced = sum(1 for i in ingredients if i.has_price)
    print(f"  {priced}/{len(ingredients)} mit Preis")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
